language: erlang

# Hack to make Travis not try to run rebar get-deps for a rebar3 project.
install: 'true'

otp_release:
    - 18.3
    - 19.0

script:
    - wget https://s3.amazonaws.com/rebar3/rebar3
    - chmod 755 rebar3
    - ./rebar3 proper
